name: Deploy to CloudBase

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Install CloudBase CLI
      run: npm install -g @cloudbase/cli
      
    - name: Deploy to CloudBase Static Hosting
      run: |
        echo "Deploying to CloudBase..."
        tcb login --apiKeyId ${{ secrets.TENCENT_SECRET_ID }} --apiKey ${{ secrets.TENCENT_SECRET_KEY }}
        tcb hosting deploy ./dist -e ${{ secrets.CLOUDBASE_ENV_ID }}
      env:
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        CLOUDBASE_ENV_ID: ${{ secrets.CLOUDBASE_ENV_ID }}
        
    - name: Deployment Success
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 Your app should be available at your CloudBase hosting URL"